services:
  mysqldb:
    image: mysql:8.0.33
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=adopet
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - adopetnet
    volumes:  
      - mysql-data:/var/lib/mysql

  api:
    container_name: adopet-api
    depends_on: 
      - mysqldb
    build: root\backend
    image: matheusp16/adopetnodeapi:v1
    environment:
      DB_NAME: adopet
      DB_USER: admin
      DB_PWD: password
      DB_HOST: mysqldb
      DB_PORT: 3306
    ports:
      - 8000:8000
    expose:
      - 8000
    networks: 
      - adopetnet

  web:
    container_name: adopet-web
    depends_on: 
      - api
    build: root\frontend
    image: matheusp16/adopetweb:v1
    ports:
      - 80:80
    expose:
      - 80
    networks: 
      - adopetnet

networks:
  adopetnet:
    driver: bridge

volumes:
  mysql-data:

   